version: "3"
services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votesapp

  springboot-app:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - db
